/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import { be_ } from '@ctx-core/object'
import type { theme_Ctx } from './theme_Ctx'
import type { invert_theme$_T } from './invert_theme$_b'
import { invert_theme$_b } from './invert_theme$_b'
import type { invert_theme_class$_T } from './invert_theme_class$_b'
import { invert_theme_class$_b } from './invert_theme_class$_b'
export interface theme_ctx_I {
	invert_theme$?:invert_theme$_T
	invert_theme_class$?:invert_theme_class$_T
	theme_b_h?:theme_b_h_T
}
export interface theme_b_h_T {
	get invert_theme$():invert_theme$_T
	get invert_theme_class$():invert_theme_class$_T
}
export function theme_b_h_b(ctx:theme_Ctx):theme_b_h_T {
	return be_<theme_Ctx, 'theme_b_h'>('theme_b_h', ()=>{
		return {
			get invert_theme$() { return invert_theme$_b(ctx) },
			get invert_theme_class$() { return invert_theme_class$_b(ctx) }
		}
	})(ctx)
}
