/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { invert_theme$_T } from './invert_theme$_b.js'
import type { invert_theme_class$_T } from './invert_theme_class$_b.js'
export interface theme_ctx_I {
	invert_theme$?:invert_theme$_T
	invert_theme_class$?:invert_theme_class$_T
}
